from django.db import models


# ── Prediction engine models ───────────────────────────────────────────────────

class Prediction(models.Model):
    """One row per pick generated by the prediction engine."""

    OUTCOME_CHOICES = [
        ('PENDING', 'Pending'),
        ('WIN',     'Win'),
        ('LOSS',    'Loss'),
        ('VOID',    'Void'),   # postponed / cancelled
    ]

    # Match identity
    match_date       = models.DateField(db_index=True)
    home_team        = models.CharField(max_length=120)
    away_team        = models.CharField(max_length=120)
    league           = models.CharField(max_length=120)
    competition_code = models.CharField(max_length=10)
    kickoff          = models.DateTimeField(null=True, blank=True)

    # The bet
    bet_type     = models.CharField(max_length=220)
    confidence   = models.IntegerField(default=0)
    grade        = models.CharField(max_length=5)
    grade_score  = models.IntegerField(default=0)
    accuracy_pct = models.FloatField(null=True, blank=True)

    # Supporting data (JSON arrays)
    evidence  = models.JSONField(default=list)
    penalties = models.JSONField(default=list)
    injuries  = models.JSONField(default=list)

    # Day of week (SAT / SUN / FRI / WED / MON / TUE / THU)
    DAY_CHOICES = [
        ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'),
        ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'),
    ]
    day_of_week = models.CharField(max_length=3, choices=DAY_CHOICES, default='SAT', db_index=True)

    # Outcome (updated by update_results command)
    outcome          = models.CharField(max_length=10, choices=OUTCOME_CHOICES, default='PENDING')
    actual_home_score = models.IntegerField(null=True, blank=True)
    actual_away_score = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('match_date', 'home_team', 'away_team', 'bet_type')
        ordering = ['-match_date', '-grade_score']

    def __str__(self):
        return f"{self.match_date} | {self.home_team} vs {self.away_team} | {self.bet_type} | {self.outcome}"

    @property
    def fixture_label(self):
        return f"{self.home_team} vs {self.away_team}"


class MatchResult(models.Model):
    """Actual full-time score for a match — populated by update_results."""

    match_date  = models.DateField(db_index=True)
    home_team   = models.CharField(max_length=120)
    away_team   = models.CharField(max_length=120)
    league_code = models.CharField(max_length=10)
    home_score  = models.IntegerField()
    away_score  = models.IntegerField()
    fetched_at  = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('match_date', 'home_team', 'away_team')
        ordering = ['-match_date']

    def __str__(self):
        return f"{self.match_date} | {self.home_team} {self.home_score}-{self.away_score} {self.away_team}"


class DailyScorecard(models.Model):
    """Computed accuracy summary per date — rebuilt by update_results."""

    date        = models.DateField(unique=True)
    total_picks = models.IntegerField(default=0)
    correct     = models.IntegerField(default=0)
    losses      = models.IntegerField(default=0)
    voids       = models.IntegerField(default=0)
    accuracy_pct = models.FloatField(default=0.0)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.date} | {self.correct}/{self.total_picks} ({self.accuracy_pct:.1f}%)"


# ── Original bet slip models ───────────────────────────────────────────────────

class BetSlip(models.Model):
    booking_code = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"BetSlip: {self.booking_code}"


class Match(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('SAFE', 'Safe'),
        ('DANGER', 'Danger'),
        ('CRITICAL', 'Critical'),
        ('WON', 'Won'),
        ('LOST', 'Lost'),
    ]

    bet_slip = models.ForeignKey(BetSlip, on_delete=models.CASCADE, related_name='matches')

    # Match identity
    fixture_id = models.IntegerField(null=True, blank=True)  # football-data.org ID
    home_team = models.CharField(max_length=100)
    away_team = models.CharField(max_length=100)
    kickoff_time = models.DateTimeField(null=True, blank=True)

    # User's selection
    user_pick = models.CharField(max_length=200)   # human-readable, e.g. "Aston Villa to score"
    market = models.CharField(max_length=200, blank=True, default='')  # raw market name from SportyBet
    odds = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    # Live data
    match_minute = models.IntegerField(null=True, blank=True)
    score_home = models.IntegerField(default=0)
    score_away = models.IntegerField(default=0)
    match_status = models.CharField(max_length=30, default='SCHEDULED')

    # Stats (deep data plan)
    possession_home = models.FloatField(null=True, blank=True)
    possession_away = models.FloatField(null=True, blank=True)
    shots_on_target_home = models.IntegerField(null=True, blank=True)
    shots_on_target_away = models.IntegerField(null=True, blank=True)
    shots_total_home = models.IntegerField(null=True, blank=True)
    shots_total_away = models.IntegerField(null=True, blank=True)
    corners_home = models.IntegerField(null=True, blank=True)
    corners_away = models.IntegerField(null=True, blank=True)
    red_cards_home = models.IntegerField(default=0)
    red_cards_away = models.IntegerField(default=0)

    # Events timeline (goals, cards, subs stored as JSON)
    events = models.JSONField(default=list)

    # Analysis result
    analysis_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    analysis_reason = models.TextField(blank=True)

    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.home_team} vs {self.away_team} ({self.bet_slip.booking_code})"


# ── Historical match database (backfill + daily update) ───────────────────────

class HistoricalFixture(models.Model):
    """One row per completed fixture — the master record for a match."""

    fixture_id   = models.IntegerField(unique=True, db_index=True)  # API-Football ID
    league_code  = models.CharField(max_length=10, db_index=True)
    league_id    = models.IntegerField()
    league_name  = models.CharField(max_length=120)
    season       = models.IntegerField(db_index=True)

    match_date   = models.DateField(db_index=True)
    kickoff      = models.DateTimeField(null=True, blank=True)
    round        = models.CharField(max_length=60, blank=True)
    venue        = models.CharField(max_length=120, blank=True)

    home_team    = models.CharField(max_length=120)
    away_team    = models.CharField(max_length=120)
    home_team_id = models.IntegerField(null=True, blank=True)
    away_team_id = models.IntegerField(null=True, blank=True)

    home_score   = models.IntegerField(null=True, blank=True)
    away_score   = models.IntegerField(null=True, blank=True)
    home_ht      = models.IntegerField(null=True, blank=True)  # half-time score
    away_ht      = models.IntegerField(null=True, blank=True)

    status       = models.CharField(max_length=30, default='FT')  # FT / AET / PEN / etc.
    winner       = models.CharField(max_length=10, blank=True)    # HOME / AWAY / DRAW

    stats_fetched   = models.BooleanField(default=False)
    lineup_fetched  = models.BooleanField(default=False)
    players_fetched = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-match_date']
        indexes = [
            models.Index(fields=['league_code', 'season', 'match_date']),
            models.Index(fields=['home_team_id', 'season']),
            models.Index(fields=['away_team_id', 'season']),
        ]

    def __str__(self):
        return f"{self.match_date} | {self.home_team} {self.home_score}-{self.away_score} {self.away_team} [{self.league_code}]"

    @property
    def total_goals(self):
        if self.home_score is not None and self.away_score is not None:
            return self.home_score + self.away_score
        return None


class MatchStats(models.Model):
    """Full match statistics for a completed fixture."""

    fixture      = models.OneToOneField(HistoricalFixture, on_delete=models.CASCADE, related_name='stats')

    # Possession
    possession_home = models.FloatField(null=True, blank=True)
    possession_away = models.FloatField(null=True, blank=True)

    # Shots
    shots_total_home = models.IntegerField(null=True, blank=True)
    shots_total_away = models.IntegerField(null=True, blank=True)
    shots_on_home    = models.IntegerField(null=True, blank=True)
    shots_on_away    = models.IntegerField(null=True, blank=True)
    shots_off_home   = models.IntegerField(null=True, blank=True)
    shots_off_away   = models.IntegerField(null=True, blank=True)
    blocked_home     = models.IntegerField(null=True, blank=True)
    blocked_away     = models.IntegerField(null=True, blank=True)

    # xG (API-Football)
    xg_home = models.FloatField(null=True, blank=True)
    xg_away = models.FloatField(null=True, blank=True)

    # Passes
    passes_total_home    = models.IntegerField(null=True, blank=True)
    passes_total_away    = models.IntegerField(null=True, blank=True)
    pass_accuracy_home   = models.FloatField(null=True, blank=True)
    pass_accuracy_away   = models.FloatField(null=True, blank=True)
    key_passes_home      = models.IntegerField(null=True, blank=True)
    key_passes_away      = models.IntegerField(null=True, blank=True)

    # Defending
    corners_home = models.IntegerField(null=True, blank=True)
    corners_away = models.IntegerField(null=True, blank=True)
    fouls_home   = models.IntegerField(null=True, blank=True)
    fouls_away   = models.IntegerField(null=True, blank=True)
    offsides_home = models.IntegerField(null=True, blank=True)
    offsides_away = models.IntegerField(null=True, blank=True)

    # Cards
    yellow_home = models.IntegerField(null=True, blank=True)
    yellow_away = models.IntegerField(null=True, blank=True)
    red_home    = models.IntegerField(null=True, blank=True)
    red_away    = models.IntegerField(null=True, blank=True)

    # Saves
    saves_home = models.IntegerField(null=True, blank=True)
    saves_away = models.IntegerField(null=True, blank=True)

    raw = models.JSONField(default=dict)  # full API response preserved

    class Meta:
        ordering = ['-fixture__match_date']

    def __str__(self):
        return f"Stats: {self.fixture}"


class MatchLineup(models.Model):
    """Starting XI + subs for one team in a fixture."""

    fixture     = models.ForeignKey(HistoricalFixture, on_delete=models.CASCADE, related_name='lineups')
    team_id     = models.IntegerField()
    team_name   = models.CharField(max_length=120)
    is_home     = models.BooleanField()
    formation   = models.CharField(max_length=20, blank=True)
    coach_name  = models.CharField(max_length=120, blank=True)

    # Starting XI and subs as JSON list of {id, name, number, pos, grid}
    starters    = models.JSONField(default=list)
    substitutes = models.JSONField(default=list)

    class Meta:
        unique_together = ('fixture', 'team_id')

    def __str__(self):
        return f"Lineup: {self.team_name} ({self.formation}) — {self.fixture.match_date}"


class PlayerMatchRating(models.Model):
    """Individual player performance in a single fixture."""

    fixture      = models.ForeignKey(HistoricalFixture, on_delete=models.CASCADE, related_name='player_ratings')
    team_id      = models.IntegerField(db_index=True)
    team_name    = models.CharField(max_length=120)
    is_home      = models.BooleanField()

    player_id    = models.IntegerField(db_index=True)
    player_name  = models.CharField(max_length=120)
    position     = models.CharField(max_length=10, blank=True)
    number       = models.IntegerField(null=True, blank=True)

    # Performance
    rating           = models.FloatField(null=True, blank=True)  # Sofascore-style 0-10
    minutes_played   = models.IntegerField(null=True, blank=True)
    was_starter      = models.BooleanField(default=True)

    # Attacking
    goals       = models.IntegerField(default=0)
    assists     = models.IntegerField(default=0)
    shots_total = models.IntegerField(null=True, blank=True)
    shots_on    = models.IntegerField(null=True, blank=True)

    # Passing
    passes_total    = models.IntegerField(null=True, blank=True)
    key_passes      = models.IntegerField(null=True, blank=True)
    pass_accuracy   = models.FloatField(null=True, blank=True)

    # Dribbles & duels
    dribbles_attempts = models.IntegerField(null=True, blank=True)
    dribbles_success  = models.IntegerField(null=True, blank=True)
    duels_total       = models.IntegerField(null=True, blank=True)
    duels_won         = models.IntegerField(null=True, blank=True)

    # Defending
    tackles         = models.IntegerField(null=True, blank=True)
    interceptions   = models.IntegerField(null=True, blank=True)
    clearances      = models.IntegerField(null=True, blank=True)

    # Cards
    yellow_card = models.BooleanField(default=False)
    red_card    = models.BooleanField(default=False)

    raw = models.JSONField(default=dict)  # full player stats block from API

    class Meta:
        unique_together = ('fixture', 'player_id')
        indexes = [
            models.Index(fields=['player_id', 'fixture']),
            models.Index(fields=['team_id', 'fixture']),
        ]

    # Extra fields from raw API (stored but not queried initially)
    fouls_drawn     = models.IntegerField(null=True, blank=True)  # fouls won by player
    penalty_won     = models.IntegerField(null=True, blank=True)
    penalty_scored  = models.IntegerField(null=True, blank=True)
    penalty_missed  = models.IntegerField(null=True, blank=True)
    penalty_saved   = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.player_name} ({self.rating}) — {self.fixture}"


# ── Understat match-level data (Big 5 leagues) ────────────────────────────────

class MatchUnderstatStats(models.Model):
    """
    Per-match Understat data — big chances, goals by situation, xG by situation.
    One row per completed fixture in the Big 5 leagues.
    """
    fixture           = models.OneToOneField(HistoricalFixture, on_delete=models.CASCADE, related_name='understat_stats')
    understat_match_id = models.CharField(max_length=20, blank=True, db_index=True)

    # Big chances (shots with xG >= 0.20)
    big_chances_home        = models.IntegerField(null=True, blank=True)
    big_chances_away        = models.IntegerField(null=True, blank=True)
    big_chances_scored_home = models.IntegerField(null=True, blank=True)
    big_chances_scored_away = models.IntegerField(null=True, blank=True)
    big_chances_missed_home = models.IntegerField(null=True, blank=True)
    big_chances_missed_away = models.IntegerField(null=True, blank=True)

    # Goals by situation
    goals_open_play_home     = models.IntegerField(null=True, blank=True)
    goals_open_play_away     = models.IntegerField(null=True, blank=True)
    goals_set_piece_home     = models.IntegerField(null=True, blank=True)  # corners + indirect FK
    goals_set_piece_away     = models.IntegerField(null=True, blank=True)
    goals_direct_fk_home     = models.IntegerField(null=True, blank=True)
    goals_direct_fk_away     = models.IntegerField(null=True, blank=True)
    goals_penalty_home       = models.IntegerField(null=True, blank=True)
    goals_penalty_away       = models.IntegerField(null=True, blank=True)

    # Shots by situation
    shots_open_play_home     = models.IntegerField(null=True, blank=True)
    shots_open_play_away     = models.IntegerField(null=True, blank=True)
    shots_set_piece_home     = models.IntegerField(null=True, blank=True)
    shots_set_piece_away     = models.IntegerField(null=True, blank=True)
    shots_penalty_home       = models.IntegerField(null=True, blank=True)
    shots_penalty_away       = models.IntegerField(null=True, blank=True)

    # xG by situation
    xg_open_play_home        = models.FloatField(null=True, blank=True)
    xg_open_play_away        = models.FloatField(null=True, blank=True)
    xg_set_piece_home        = models.FloatField(null=True, blank=True)
    xg_set_piece_away        = models.FloatField(null=True, blank=True)
    xg_penalty_home          = models.FloatField(null=True, blank=True)
    xg_penalty_away          = models.FloatField(null=True, blank=True)

    # Shot types
    shots_head_home          = models.IntegerField(null=True, blank=True)
    shots_head_away          = models.IntegerField(null=True, blank=True)
    shots_right_foot_home    = models.IntegerField(null=True, blank=True)
    shots_right_foot_away    = models.IntegerField(null=True, blank=True)
    shots_left_foot_home     = models.IntegerField(null=True, blank=True)
    shots_left_foot_away     = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-fixture__match_date']

    def __str__(self):
        return f"Understat: {self.fixture}"


class PlayerUnderstatStats(models.Model):
    """
    Per-player Understat stats for one match — xG, xA, shots by situation/type.
    Only available for Big 5 leagues.
    """
    fixture      = models.ForeignKey(HistoricalFixture, on_delete=models.CASCADE, related_name='understat_players')
    understat_player_id = models.CharField(max_length=20, db_index=True)
    player_name  = models.CharField(max_length=120)
    team_name    = models.CharField(max_length=120)
    is_home      = models.BooleanField()

    # Core stats from rosters
    xg           = models.FloatField(null=True, blank=True)
    xa           = models.FloatField(null=True, blank=True)
    shots        = models.IntegerField(null=True, blank=True)
    key_passes   = models.IntegerField(null=True, blank=True)
    goals        = models.IntegerField(default=0)
    assists      = models.IntegerField(default=0)
    own_goals    = models.IntegerField(default=0)
    minutes      = models.IntegerField(null=True, blank=True)
    yellow       = models.IntegerField(default=0)
    red          = models.IntegerField(default=0)

    # Shot type breakdown (from shots data)
    shots_head        = models.IntegerField(null=True, blank=True)
    shots_right_foot  = models.IntegerField(null=True, blank=True)
    shots_left_foot   = models.IntegerField(null=True, blank=True)

    # Shot situation breakdown
    shots_open_play      = models.IntegerField(null=True, blank=True)
    shots_from_corner    = models.IntegerField(null=True, blank=True)
    shots_direct_fk      = models.IntegerField(null=True, blank=True)
    shots_set_piece      = models.IntegerField(null=True, blank=True)
    shots_penalty        = models.IntegerField(null=True, blank=True)

    # Big chance stats
    big_chances_scored = models.IntegerField(null=True, blank=True)
    big_chances_missed = models.IntegerField(null=True, blank=True)

    class Meta:
        unique_together = ('fixture', 'understat_player_id')
        indexes = [
            models.Index(fields=['understat_player_id', 'fixture']),
        ]

    def __str__(self):
        return f"{self.player_name} xG:{self.xg} xA:{self.xa} — {self.fixture}"
