# Generated by Django 6.0.3 on 2026-03-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('kickoff_time', models.DateTimeField(blank=True, null=True)),
                ('user_pick', models.CharField(max_length=100)),
                ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('match_minute', models.IntegerField(blank=True, null=True)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
                ('match_status', models.CharField(default='SCHEDULED', max_length=30)),
                ('possession_home', models.FloatField(blank=True, null=True)),
                ('possession_away', models.FloatField(blank=True, null=True)),
                ('shots_on_target_home', models.IntegerField(blank=True, null=True)),
                ('shots_on_target_away', models.IntegerField(blank=True, null=True)),
                ('shots_total_home', models.IntegerField(blank=True, null=True)),
                ('shots_total_away', models.IntegerField(blank=True, null=True)),
                ('corners_home', models.IntegerField(blank=True, null=True)),
                ('corners_away', models.IntegerField(blank=True, null=True)),
                ('red_cards_home', models.IntegerField(default=0)),
                ('red_cards_away', models.IntegerField(default=0)),
                ('events', models.JSONField(default=list)),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('SAFE', 'Safe'), ('DANGER', 'Danger'), ('CRITICAL', 'Critical'), ('WON', 'Won'), ('LOST', 'Lost')], default='PENDING', max_length=20)),
                ('analysis_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bets.betslip')),
            ],
        ),
    ]
