# Generated by Django 6.0.3 on 2026-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='market',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_pick',
            field=models.CharField(max_length=200),
        ),
    ]
