# Generated by Django 6.0.3 on 2026-04-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_historical_fixture_stats_lineup_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchrating',
            name='fouls_drawn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='penalty_missed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='penalty_saved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='penalty_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='penalty_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchUnderstatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understat_match_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('big_chances_home', models.IntegerField(blank=True, null=True)),
                ('big_chances_away', models.IntegerField(blank=True, null=True)),
                ('big_chances_scored_home', models.IntegerField(blank=True, null=True)),
                ('big_chances_scored_away', models.IntegerField(blank=True, null=True)),
                ('big_chances_missed_home', models.IntegerField(blank=True, null=True)),
                ('big_chances_missed_away', models.IntegerField(blank=True, null=True)),
                ('goals_open_play_home', models.IntegerField(blank=True, null=True)),
                ('goals_open_play_away', models.IntegerField(blank=True, null=True)),
                ('goals_set_piece_home', models.IntegerField(blank=True, null=True)),
                ('goals_set_piece_away', models.IntegerField(blank=True, null=True)),
                ('goals_direct_fk_home', models.IntegerField(blank=True, null=True)),
                ('goals_direct_fk_away', models.IntegerField(blank=True, null=True)),
                ('goals_penalty_home', models.IntegerField(blank=True, null=True)),
                ('goals_penalty_away', models.IntegerField(blank=True, null=True)),
                ('shots_open_play_home', models.IntegerField(blank=True, null=True)),
                ('shots_open_play_away', models.IntegerField(blank=True, null=True)),
                ('shots_set_piece_home', models.IntegerField(blank=True, null=True)),
                ('shots_set_piece_away', models.IntegerField(blank=True, null=True)),
                ('shots_penalty_home', models.IntegerField(blank=True, null=True)),
                ('shots_penalty_away', models.IntegerField(blank=True, null=True)),
                ('xg_open_play_home', models.FloatField(blank=True, null=True)),
                ('xg_open_play_away', models.FloatField(blank=True, null=True)),
                ('xg_set_piece_home', models.FloatField(blank=True, null=True)),
                ('xg_set_piece_away', models.FloatField(blank=True, null=True)),
                ('xg_penalty_home', models.FloatField(blank=True, null=True)),
                ('xg_penalty_away', models.FloatField(blank=True, null=True)),
                ('shots_head_home', models.IntegerField(blank=True, null=True)),
                ('shots_head_away', models.IntegerField(blank=True, null=True)),
                ('shots_right_foot_home', models.IntegerField(blank=True, null=True)),
                ('shots_right_foot_away', models.IntegerField(blank=True, null=True)),
                ('shots_left_foot_home', models.IntegerField(blank=True, null=True)),
                ('shots_left_foot_away', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='understat_stats', to='bets.historicalfixture')),
            ],
            options={
                'ordering': ['-fixture__match_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerUnderstatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understat_player_id', models.CharField(db_index=True, max_length=20)),
                ('player_name', models.CharField(max_length=120)),
                ('team_name', models.CharField(max_length=120)),
                ('is_home', models.BooleanField()),
                ('xg', models.FloatField(blank=True, null=True)),
                ('xa', models.FloatField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('key_passes', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('yellow', models.IntegerField(default=0)),
                ('red', models.IntegerField(default=0)),
                ('shots_head', models.IntegerField(blank=True, null=True)),
                ('shots_right_foot', models.IntegerField(blank=True, null=True)),
                ('shots_left_foot', models.IntegerField(blank=True, null=True)),
                ('shots_open_play', models.IntegerField(blank=True, null=True)),
                ('shots_from_corner', models.IntegerField(blank=True, null=True)),
                ('shots_direct_fk', models.IntegerField(blank=True, null=True)),
                ('shots_set_piece', models.IntegerField(blank=True, null=True)),
                ('shots_penalty', models.IntegerField(blank=True, null=True)),
                ('big_chances_scored', models.IntegerField(blank=True, null=True)),
                ('big_chances_missed', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='understat_players', to='bets.historicalfixture')),
            ],
            options={
                'indexes': [models.Index(fields=['understat_player_id', 'fixture'], name='bets_player_underst_2b406d_idx')],
                'unique_together': {('fixture', 'understat_player_id')},
            },
        ),
    ]
